# zmodload zsh/zprof
autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit
[ -e /etc/profile ] && emulate sh -c 'source /etc/profile'

# We still need the following line since nvm.sh will search it
# [ -e ~/.nvm ] && export NVM_DIR=~/.nvm && \. "$NVM_DIR/nvm.sh"
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"


source ~/.term-tools/config/shrc.sh

pathprepend() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="$1${PATH:+":$PATH"}"
    fi
}
pathprepend "/usr/local/cuda/bin"
pathprepend "$HOME/.local/bin"
# export PATH=/usr/local/bin:/usr/local/cuda/bin:/usr/bin:/bin:/usr/sbin:/sbin

if [[ "$OSTYPE" == "darwin"* ]]; then
    true
else
    true
fi

alias compile_commands='ninja -t compdb $(grep ^rule build.ninja rules.ninja | awk "{print $2}") | sed "s@clang++ @clang++ $LIBCPP_DIR @" > compile_commands.json'
# zprof
[[ -n $SHELL_VENV_DEFAULT_PATH ]] && [[ -d $SHELL_VENV_DEFAULT_PATH ]] && source "$SHELL_VENV_DEFAULT_PATH/bin/activate"
